package.json
=> chore: Turn on npm publish

package-lock.json, package.json, projects/stream-chat-angular/src/assets/version.ts, projects/stream-chat-angular/src/lib/chat-client.service.spec.ts, projects/stream-chat-angular/src/lib/chat-client.service.ts, projects/stream-chat-angular/src/lib/mocks/index.ts, set-version.sh
=> feat: Add SDK header #64

tutorial/tutorial.md
=> docs: Fix tutorial after testing

docusaurus/docs/Angular/components/message-input.mdx, docusaurus/docs/Angular/components/message-list.mdx, docusaurus/docs/Angular/components/message.mdx, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
=> feat: Implement channel capabilities #63

package-lock.json, package.json, projects/stream-chat-angular/package.json, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts
=> fix: Empty messages can be sent #133

docusaurus/docs/Angular/components/channel.mdx, docusaurus/docs/Angular/services/channel.mdx, docusaurus/docs/Angular/services/chat-client.mdx, tutorial/tutorial.md
=> docs: Enhance tutorial and docs

angular.json, docusaurus/docs/Angular/components/autocomplete-textarea.mdx, package-lock.json, package.json, projects/stream-chat-angular/ng-package.json, projects/stream-chat-angular/package.json, projects/stream-chat-angular/src/lib/message-input/autocomplete-textarea/autocomplete-textarea.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/autocomplete-textarea/autocomplete-textarea.component.ts, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.html, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.spec.ts, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.ts, projects/stream-chat-angular/src/lib/stream-chat.module.ts, projects/stream-chat-angular/src/lib/transliteration.service.ts, projects/stream-chat-angular/src/public-api.ts
=> feat: Add transliteration #145

docusaurus/docs/Angular/components/channel-header.mdx, docusaurus/docs/Angular/components/message-input.mdx, docusaurus/docs/Angular/components/message.mdx, projects/stream-chat-angular/src/assets/i18n/en.ts, projects/stream-chat-angular/src/lib/channel-header/channel-header.component.html, projects/stream-chat-angular/src/lib/channel-header/channel-header.component.spec.ts, projects/stream-chat-angular/src/lib/channel-header/channel-header.component.ts, projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.spec.ts, projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
=> feat: Implement missing channel capabilities #136

docusaurus/docs/Angular/components/message-actions.mdx, docusaurus/docs/Angular/components/message-input.mdx, docusaurus/docs/Angular/components/message-list.mdx, docusaurus/docs/Angular/components/message.mdx, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.html, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.ts
=> feat: Add support for custom message input in MessageActionsBox #134

docusaurus/docs/Angular/concepts/change-detection.mdx, docusaurus/docs/Angular/services/channel.mdx, docusaurus/docs/Angular/services/chat-client.mdx, projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/chat-client.service.spec.ts, projects/stream-chat-angular/src/lib/chat-client.service.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
=> fix: Add missing ngZone reenters

package-lock.json, package.json, projects/stream-chat-angular/package.json, projects/stream-chat-angular/src/lib/attachment-preview-list/attachment-preview-list.component.html, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.html, projects/stream-chat-angular/src/lib/message/message.component.html
stream-chat-css PR: https://github.com/GetStream/stream-chat-css/pull/30
=> Version bump stream-chat, @stream-io/stream-chat-css

docusaurus/docs/Angular/services/channel.mdx, docusaurus/docs/Angular/services/chat-client.mdx, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/chat-client.service.spec.ts, projects/stream-chat-angular/src/lib/chat-client.service.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
closes #182 
This is for Dillion's chat app
=> feat: Disconnect user #182

docusaurus/docs/Angular/components/message-actions.mdx, docusaurus/docs/Angular/concepts/message-interactions.mdx, docusaurus/docs/Angular/services/channel.mdx, package-lock.json, package.json, projects/stream-chat-angular/package.json, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.thread.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/icon/icon.component.html, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.spec.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message-preview.spec.ts, projects/stream-chat-angular/src/lib/message-preview.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
CSS: https://github.com/GetStream/stream-chat-css/pull/37
closes #174
=> feat: Quote reply to messages #174

projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts
=> fix: Close message actions on mouseleave #177

projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.html
=> fix: Reactions cursor #178

docusaurus/docs/Angular/basics/upgrade-v2.mdx, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.ts, projects/stream-chat-angular/src/lib/message-input/message-input-config.service.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
BREAKING CHANGE: Deprecated inputs are removed
See our docs on how to upgrade
closes #213
=> feat: Remove deprecated inputs

README.md, docusaurus/docs/Angular/components/AttachmentListComponent.mdx, docusaurus/docs/Angular/components/AttachmentPreviewListComponent.mdx, docusaurus/docs/Angular/components/AvatarComponent.mdx, docusaurus/docs/Angular/components/ChannelHeaderComponent.mdx, docusaurus/docs/Angular/components/ChannelListComponent.mdx, docusaurus/docs/Angular/components/ChannelPreviewComponent.mdx, docusaurus/docs/Angular/components/IconComponent.mdx, docusaurus/docs/Angular/components/LoadingIndicatorComponent.mdx, docusaurus/docs/Angular/components/MessageActionsBoxComponent.mdx, docusaurus/docs/Angular/components/MessageComponent.mdx, docusaurus/docs/Angular/components/MessageInputComponent.mdx, docusaurus/docs/Angular/components/MessageListComponent.mdx, docusaurus/docs/Angular/components/MessageReactionsComponent.mdx, docusaurus/docs/Angular/components/ModalComponent.mdx, docusaurus/docs/Angular/components/NotificationComponent.mdx, docusaurus/docs/Angular/components/NotificationListComponent.mdx, docusaurus/docs/Angular/components/ThreadComponent.mdx, docusaurus/docs/Angular/concepts/customization.mdx, projects/customizations-example/src/app/app.component.html, projects/customizations-example/src/app/app.component.ts, projects/customizations-example/src/app/app.module.ts, projects/customizations-example/src/app/emoji-picker/emoji-picker.component.html, projects/customizations-example/src/app/icon/icon.component.html, projects/customizations-example/src/app/icon/icon.component.scss, projects/customizations-example/src/app/icon/icon.component.spec.ts, projects/customizations-example/src/app/icon/icon.component.ts, projects/customizations-example/src/app/thread-header/thread-header.component.scss, projects/customizations-example/src/styles.scss, projects/stream-chat-angular/src/lib/custom-templates.service.ts
=> Customization guide

.gitignore, docusaurus/docs/Angular/basics/upgrade-v2.mdx, package-lock.json, package.json, projects/customizations-example/src/styles.scss, projects/sample-app/src/styles.scss, projects/stream-chat-angular/ng-package.json, projects/stream-chat-angular/package.json
=> Encapsulate stream chat css

docusaurus/docs/Angular/basics/upgrade-v2.mdx, docusaurus/docs/Angular/concepts/generics.mdx, package-lock.json, package.json, projects/stream-chat-angular/package.json, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.spec.ts, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.ts, projects/stream-chat-angular/src/lib/channel-header/channel-header.component.ts, projects/stream-chat-angular/src/lib/channel-list/channel-list.component.ts, projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.thread.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/chat-client.service.spec.ts, projects/stream-chat-angular/src/lib/chat-client.service.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/autocomplete-textarea/autocomplete-textarea.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message-preview.spec.ts, projects/stream-chat-angular/src/lib/message-preview.ts, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.ts, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts, projects/stream-chat-angular/src/lib/read-by.spec.ts, projects/stream-chat-angular/src/lib/read-by.ts, projects/stream-chat-angular/src/lib/types.ts
I wasn't able to find the TypeScript problem
I'll update the code examples as part of my final testing
closes #215
=> Stream chat v6

projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts
=> feat: Add custom attachment requests #255

package-lock.json, package.json, projects/stream-chat-angular/src/lib/icon/icon.component.html, projects/stream-chat-angular/src/lib/icon/icon.component.spec.ts, projects/stream-chat-angular/src/lib/icon/icon.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts
=> feat: Message list supports top to bottom layout #212

projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts
=> feat: Make it possible to pause read events #267

docusaurus/docs/Angular/code-examples/_category_.json, docusaurus/docs/Angular/code-examples/channel-invites.mdx, docusaurus/docs/Angular/concepts/_category_.json, docusaurus/docs/Angular/concepts/customization.mdx, docusaurus/docs/Angular/concepts/theming-and-css.mdx, docusaurus/docs/Angular/theming/_category_.json, docusaurus/docs/Angular/theming/component-variables.mdx, docusaurus/docs/Angular/theming/introduction.mdx, docusaurus/docs/Angular/theming/theme-variables.mdx, projects/stream-chat-angular/src/lib/theme.service.ts
=> docs: Document theme and component layer variables #289

docusaurus/docs/Angular/code-examples/emoji-picker.mdx, projects/sample-app/src/app/app.component.ts, projects/sample-app/src/app/emoji-picker/emoji-picker.component.html, projects/sample-app/src/app/emoji-picker/emoji-picker.component.scss, projects/sample-app/src/app/emoji-picker/emoji-picker.component.ts, projects/stream-chat-angular/src/lib/message-input/autocomplete-textarea/autocomplete-textarea.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts
The second part of message input implementation:
Implementation
Figma
Implementation
**Note** list of commands comes from the backend, and it's dynamic so it's not trivial to display icons for them
Figma
Implementation
Figma
Implementation
**Note** The quoted message UI will be part of this issue: https://github.com/GetStream/stream-chat-css/issues/94
closes #283
=> feat: Message input theme-v2 missing features #283

projects/stream-chat-angular/src/assets/i18n/en.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts
closes #281 
Theme-v1 updated:
=> feat: Apply theme-v2 to typing indicator #281

.github/workflows/workflow.yml, .gitignore, copy-css-docs.sh, package.json
Scripts for copying CSS docs into Angular SDK locally and from CI
=> chore: Copy-css docs

.github/workflows/workflow.yml, projects/stream-chat-angular/src/lib/chat-client.service.spec.ts, projects/stream-chat-angular/src/lib/chat-client.service.ts
=> feat: Define user$ Observable #338

projects/stream-chat-angular/src/lib/attachment.service.spec.ts, projects/stream-chat-angular/src/lib/attachment.service.ts
=> fix: Video attachments disappear during message edit #323

projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
=> fix: Message component throws error if chatClient is not defined

projects/stream-chat-angular/src/lib/avatar/avatar.component.html, projects/stream-chat-angular/src/lib/avatar/avatar.component.spec.ts, projects/stream-chat-angular/src/lib/avatar/avatar.component.ts
=> feat: Display other user's image in 1:1 channels #380

projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
=> fix: Stop watching channels removed from the channel list #383

projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.spec.ts, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.ts, projects/stream-chat-angular/src/lib/types.ts
The scrolling problem isn't solved entirely, but it should be better.
I also found two other issues:
- https://github.com/GetStream/stream-chat-angular/issues/399
- https://github.com/GetStream/stream-chat-angular/issues/398
But that's all the time I had for now
=> Ios scroll issues

package-lock.json, package.json, projects/stream-chat-angular/src/lib/avatar/avatar.component.html, projects/stream-chat-angular/src/lib/avatar/avatar.component.spec.ts, projects/stream-chat-angular/src/lib/avatar/avatar.component.ts
Draft: wait for stream-chat-css release
=> feat: Add online indicator for 1:1 channel avatars

docusaurus/docs/Angular/components/AttachmentListComponent.mdx, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.html, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.ts, projects/stream-chat-angular/src/lib/custom-templates.service.ts, projects/stream-chat-angular/src/lib/types.ts
=> feat: atttachment UI overrides by type #232

.github/workflows/workflow.yml, README.md, docusaurus/docs/Angular/basics/overview.mdx, package.json, projects/stream-chat-angular/package.json, projects/stream-chat-angular/src/assets/version.ts
=> Angular v16 support

projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts
=> fix: User typing indicator persists when chaning channels

package-lock.json, package.json, projects/stream-chat-angular/.eslintrc.json, projects/stream-chat-angular/package.json, projects/stream-chat-angular/src/lib/custom-templates.service.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/types.ts
=> feat: Option to jump to latest unread message

README.md
Based on the compatibility table at https://github.com/ngx-translate/core#installation
=> Added versions of @ngx-translate/core to readme

projects/customizations-example/src/app/app.component.html, projects/customizations-example/src/app/app.component.scss, projects/customizations-example/src/app/app.component.ts, projects/customizations-example/src/styles.scss, projects/stream-chat-angular/src/lib/custom-templates.service.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts
=> Empty channel placeholder

projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts
=> fix: don't call stop watch for deleted channel

package-lock.json, package.json, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
=> Frozen channels

package-lock.json, package.json, projects/stream-chat-angular/src/assets/i18n/en.ts, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.html, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.spec.ts, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
You need to update autoprefixer for version 10.2.5. Example code:
```
"overrides": {"@angular-devkit/build-angular": {"postcss-preset-env": "^7.5.0"}}
```
=> feat: display all reacting users in message reactions

projects/customizations-example/src/app/app.component.html, projects/customizations-example/src/app/app.component.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.spec.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.ts, projects/stream-chat-angular/src/lib/message-actions.service.spec.ts, projects/stream-chat-angular/src/lib/message-actions.service.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message-reactions.service.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts, projects/stream-chat-angular/src/lib/types.ts, projects/stream-chat-angular/src/public-api.ts
This refactor will enable the following features:
- Performance optimization of the message component
- Better customization of the message menu
=> refactor: Move logic from MessageActionsBox to MessageActionsService

.github/workflows/workflow.yml, package.json, projects/stream-chat-angular/package.json, projects/stream-chat-angular/src/assets/version.ts, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.html, projects/stream-chat-angular/src/lib/attachment-preview-list/attachment-preview-list.component.html, projects/stream-chat-angular/src/lib/avatar/avatar.component.html, projects/stream-chat-angular/src/lib/channel-list/channel-list.component.html, projects/stream-chat-angular/src/lib/message-input/autocomplete-textarea/autocomplete-textarea.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.html, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html
=> Remove style attributes from templates

projects/stream-chat-angular/src/lib/message-input/message-input.component.html
=> fix: remove unnecessary emoji picker container from message input #579

projects/stream-chat-angular/src/lib/avatar/avatar.component.spec.ts, projects/stream-chat-angular/src/lib/avatar/avatar.component.ts
=> fix: online indicator mistakenly displayed on avatar sometimes #576

package-lock.json, package.json
=> fix: too specific font-family setting #603

projects/customizations-example/src/app/icon/icon.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html
=> fix: autoclose works for messageActionsBoxTemplate$

projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
=> fix: url parsing errors #612

projects/stream-chat-angular/src/lib/message-actions.service.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.ts
=> fix: multiple message menus can be opened on mobile

.github/workflows/workflow.yml, package.json, projects/stream-chat-angular/package.json, projects/stream-chat-angular/src/assets/version.ts, projects/stream-chat-angular/src/lib/voice-recorder/audio-recorder.service.ts
=> Fix voice recording
