GetStream/stream-chat-angular

docusaurus/docs/Angular/components/message-reactions.mdx
The links changed currently point to `https://getstream.io/chat/docs/sdk/angular/components/message-reactions/(https://github.com/GetStream/stream-chat-angular/tree/master/projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.ts)/`.
These were reported as broken by the docusaurus validator.
=> docs: Fix broken markdown links

docusaurus/docs/Angular/components/message-actions.mdx, docusaurus/docs/Angular/components/message-input.mdx, docusaurus/docs/Angular/components/message-list.mdx, docusaurus/docs/Angular/components/message.mdx, docusaurus/docs/Angular/concepts/message-interactions.mdx, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.spec.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
In this PR:
- deprecated the inputs from the message list that can be set using channel capabilities
- combined all capability related inputs of the message component under the `enabledActions` input (old inputs are still working but deprecated)
- deprecated the SDK specific action names (like edit or delete) in favor of the capability names
=> refactor: Message action inputs and capability checks

projects/stream-chat-angular/src/lib/theme.service.spec.ts, projects/stream-chat-angular/src/lib/theme.service.ts
=> fix: Immediately apply changes to theme variables #188

projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts
=> feat: Disable message sendind during slow mode #205

projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
The Chrome emoji bug fix breaks skin toned emoji displays on Safari (https://getstream.zendesk.com/agent/tickets/20049). Since I couldn't find a CSS solution that worked on both browsers, I decided to only apply the fix to Chrome. Checked the solution on Chrome, Safari, Opera and Firefox (both with retina and non-retina resolution)
=> fix: Skin toned emoji display for Safari

docusaurus/docs/Angular/basics/upgrade-v2.mdx, projects/customizations-example/src/app/message-action/message-action.component.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.spec.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.ts, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/types.ts
**BREAKING CHANGE** see our documentation on how to upgrade
closes #234 
GH issue to implement pin action:  https://github.com/GetStream/stream-chat-angular/issues/240
=> feat: Remove custom action names and mute action

package-lock.json, package.json, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts
=> Fix message with spaces

projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts
=> fix: Empty channel preview text can't be translated #265

docusaurus/docs/Angular/concepts/theming-and-css.mdx, docusaurus/docs/Angular/theming/component-variables.mdx, docusaurus/docs/Angular/theming/theme-variables.mdx, projects/sample-app/src/app/app.component.scss, projects/stream-chat-angular/src/lib/channel-list/channel-list.component.html, projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.html, projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.spec.ts, projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts, projects/stream-chat-angular/src/lib/icon/icon.component.html, projects/stream-chat-angular/src/lib/icon/icon.component.spec.ts, projects/stream-chat-angular/src/lib/icon/icon.component.ts, projects/stream-chat-angular/src/lib/loading-indicator-placeholder/loading-indicator-placeholder.component.spec.ts, projects/stream-chat-angular/src/lib/loading-indicator-placeholder/loading-indicator-placeholder.component.ts, projects/stream-chat-angular/src/lib/loading-indicator/loading-indicator.component.ts
There are some differences between Figma and implementations, the main reasons:
- Figma has features that are not supported by (Angular) SDK
- We try not to modify the HTML markup to be compatible with theme-v1
No screenshots for responsive layout, that will added to the sample app in this issue: https://github.com/GetStream/stream-chat-angular/issues/284
| Figma  | Implementation |  Remark |
| ------------- | ------------- |------------- |
|   <img width="258" alt="Screenshot 2022-05-16 at 10 23 38" src="https://user-images.githubusercontent.com/6690098/168550674-0da27d0b-db9a-400a-a624-c4b9c46ee3f2.png">| <img width="258" alt="Screenshot 2022-05-13 at 12 43 49" src="https://user-images.githubusercontent.com/6690098/168550798-33d22ab3-3c84-4f0a-9535-4e8124e907f0.png"> | Selected state: …
=> feat: Apply theme-v2 to channel list and preview #285

projects/stream-chat-angular/src/assets/i18n/en.ts, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.html, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.spec.ts, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.ts, projects/stream-chat-angular/src/lib/icon/icon.component.html, projects/stream-chat-angular/src/lib/icon/icon.component.spec.ts, projects/stream-chat-angular/src/lib/icon/icon.component.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
Leftover issue with enhancements: https://github.com/GetStream/stream-chat-css/issues/115
**Note**: Matching the read state UI is part of the enhancement issue  https://github.com/GetStream/stream-chat-css/issues/115
**Note**: Error message is displayed for UX reasons
**Note** We should apply "own message" styling to the original message when user replies to own message, this is part of the enhancement issue: https://github.com/GetStream/stream-chat-css/issues/115 
**Note** Missing parts are included in the enhancement issue: https://github.com/GetStream/stream-chat-css/issues/115, context menu currently has a static position -> it can easily overflow -> I'll spend some limited time to implement dynamic positioning, this will come in a separate PR if successful
**Note** Image carousel …
=> Message theme v2

projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.html, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.spec.ts, projects/stream-chat-angular/src/lib/message-reactions/message-reactions.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html
closes #279 
(simplified version)
**Notes**
- Tooltip sometimes is really narrow (depends on the number of reactions, and the position of the reaction): fixing that is part of the context menu fix: https://github.com/GetStream/stream-chat-angular/issues/302 
- This is a simplistic UI - this is the enhancement issue to create the intended design: https://github.com/GetStream/stream-chat-css/issues/122
- The original design contains the reaction selector inside the message actions box - implementing that design is part of this issue: https://github.com/GetStream/stream-chat-css/issues/115 
- Currently the reaction selector isn't positioned relative to the 🙂 button, but relative to the message component - this is due to the current markup, couldn't really find a better solution - the bright …
=> feat: Message reactions #279

projects/sample-app/src/app/emoji-picker/emoji-picker.component.ts, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.html, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.html, projects/stream-chat-angular/src/lib/message-input/autocomplete-textarea/autocomplete-textarea.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/autocomplete-textarea/autocomplete-textarea.component.ts, projects/stream-chat-angular/src/lib/message-input/textarea/textarea.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/textarea/textarea.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/modal/modal.component.html
The modal component is displayed in the following use-cases:
**Enhancement issue for full Figma design**: https://github.com/GetStream/stream-chat-css/issues/126
Modal height grows with input size until max height is reached.
Known issue: The only way I could do the dynamic height of the modal was with `flax-basis`, but Safari doesn't support [flex-basis: min-content](https://caniuse.com/mdn-css_properties_flex-basis_min-content) so the modal is always max height there (see: https://github.com/GetStream/stream-chat-css/pull/127/files#diff-81e3a83444bc00479e86d1e5b47952fdb3fc042e95e3c4ec9adb4f396f0ca646R41)
It'd be also nice to have dynamic width as well, but I wasn't able to do it (it was either max width or the content overflowed) - **UPDATE** found the solution
I'm sure there is a …
=> feat: Modal component theme-v2 #278

docusaurus/docs/Angular/code-examples/responsive-layout.mdx, docusaurus/docs/Angular/components/ChannelComponent.mdx, docusaurus/docs/Angular/components/NotificationListComponent.mdx, docusaurus/docs/Angular/concepts/customization.mdx, projects/sample-app/src/app/app.component.html, projects/sample-app/src/app/app.component.ts, projects/stream-chat-angular/src/assets/i18n/en.ts, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/channel/channel.component.html, projects/stream-chat-angular/src/lib/chat-client.service.spec.ts, projects/stream-chat-angular/src/lib/chat-client.service.ts, projects/stream-chat-angular/src/lib/notification-list/notification-list.component.html, projects/stream-chat-angular/src/lib/notification-list/notification-list.component.spec.ts, projects/stream-chat-angular/src/lib/notification-list/notification-list.component.ts, projects/stream-chat-angular/src/lib/notification/notification.component.html
closes #277 
For the notification positioning, we should take into account the edit message modal, notifications should also be visible when this modal is open - I ended up positioning the notifications at the middle-bottom of the screen so they look ok with the modal open as well - will also discuss this with Fra after he is back in the office
=> Notifications theme v2

projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.spec.ts, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.ts, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.thread.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts, projects/stream-chat-angular/src/lib/types.ts
=> Fix gif delete in threads

projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts
After `message.updated` or `message.deleted` WS events the order of messages can change (the timestamp of a message can change), and messages can be deleted from the list (if we used hard delete) -> the SDK didn't account for those use-cases before, this is a fix for that
=> fix: Message update event handler doesn't respect order change and deletion

projects/stream-chat-angular/src/lib/chat-client.service.spec.ts, projects/stream-chat-angular/src/lib/chat-client.service.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
The plan is to use [guest user authentication](https://getstream.io/chat/docs/javascript/authless_users/?language=javascript#guest-users) for the theming blog post playground
=> feat: Add guest user connection option

projects/stream-chat-angular/src/assets/i18n/en.ts, projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.thread.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts, projects/stream-chat-angular/src/lib/types.ts
Jump to quoted message implemented:
- Scroll to message added inside message list
- Message list looks for unread messages even if the user is switched to an older messages list -> at the moment the message list does this by subscribing to `message.new` events, but a more Angulary solution would be: https://github.com/GetStream/stream-chat-angular/issues/369 - didn't want to invest the time now as pinned messages in itself is a big feature, but would be nice to do in the future
- Channel preview displays latest message using `channel.state.latestMessages` instead of `channel.state.messages`
- Bidirectional message load -> newer messages can be loaded if user scrolls down -> 
@petyosi just an FYI, I kept an eye for the page size problems for the message jump but didn't (yet) notice it, I'm …
=> Scroll to quoted message

projects/stream-chat-angular/src/assets/i18n/en.ts, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.spec.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
The final piece of the pin message functionality:
- pin and unpin actions implemented
- activeChannelPinnedMessages$ stream added to ChannelService
- No UI for pinned messages but integrators can inject their template inside the channel component (+ use `channelService.jumpToMessage` functionality to jump to the pinned message)
I'll create a guide for this, but with theme-v2 design and screenshots
=> feat: Pin messages

projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts
If we changed from a channel with a message list that has a scrollbar to a channel whose message list didn't, then the jump to the latest button appeared unnecessarily.
This problem was caused by the fact that a scroll event was when the message list didn't have a scrollbar (my guess is the scroll event happened in response to the height change in the message list, but not sure about that).
=> fix: Jump to latest button appears if changed to an empty channel

projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message/message.component.html
The problem: in Ionic apps on iOS Safari the hover actions didn't work - we don't seem to have this problem outside of Ionic, not sure about the reason for this
=> fix: Ionic hover problems in Safari

projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.thread.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts
Prioritizing this for a client: on mobile app if the app is paused the WS connection is closed, and when you resume a reconnect happens, so the shortcomings of the reconnect logic is more apparent there
closes #350
=> feat: Enhance reconnect #350

projects/stream-chat-angular/src/lib/read-by.spec.ts, projects/stream-chat-angular/src/lib/read-by.ts
=> fix: read by data is based on message.created_at #402

projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts
=> fix: Don't reset message input on channel update

projects/stream-chat-angular/src/lib/avatar-placeholder/avatar-placeholder.component.html, projects/stream-chat-angular/src/lib/avatar-placeholder/avatar-placeholder.component.ts
=> feat: display empty div for not visible avatars

projects/sample-app/src/app/app.component.html, projects/sample-app/src/app/app.component.ts, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.html, projects/stream-chat-angular/src/lib/attachment-list/attachment-list.component.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/chat-client.service.ts, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.html, projects/stream-chat-angular/src/lib/message-actions-box/message-actions-box.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
=> Optimization

projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
This addresses the following issue which has already been approved:
* resolves #550 
We're highly interested in seeing this issue through. Currently, clicking on links leaves our entire application which is quite jarring for our customers and makes it difficult to return to our application. Additionally, since we provide our webapp as a native app via [Capacitorjs](https://capacitorjs.com/), this could leave the user without any method of finding our app, short of quitting it and reopening it. Hitting the back navigation button may help, but it also may not always be available on our simple 
Making this adjustment became really straightforward because of the clarity of the current codebase. Similar to #558, this PR adjusts the behavior of the `Message:wrapLinksWithAnchorTag()` method to …
=> Open links in new tab

docusaurus/angular_versioned_docs/version-5/basics/upgrade-v4.mdx, projects/stream-chat-angular/src/lib/message-reactions.service.ts
BREAKING CHANGE: the `angry` reaction is removed
closes #310
=> feat: align the default reaction set with other SDKs #310

package-lock.json, package.json, projects/stream-chat-angular/.eslintrc.json, projects/stream-chat-angular/src/lib/avatar/avatar.component.ts, projects/stream-chat-angular/src/lib/channel-list/channel-list.component.ts, projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/message-actions.service.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.html, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts, projects/stream-chat-angular/src/lib/types.ts, projects/stream-chat-angular/src/lib/virtualized-list.service.spec.ts, projects/stream-chat-angular/src/lib/virtualized-list.service.ts, projects/stream-chat-angular/src/lib/virtualized-message-list.service.spec.ts, projects/stream-chat-angular/src/lib/virtualized-message-list.service.ts, projects/stream-chat-angular/src/lib/voice-recording/voice-recording.component.ts, projects/stream-chat-angular/src/public-api.ts
=> Message list more optimizations

projects/stream-chat-angular/src/lib/channel.service.spec.ts, projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.spec.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/mocks/index.ts
…age to jump to when opening the channel
=> fix: delay jumping to last read message to allow precedence to channelService.jumpToMessage

package-lock.json, package.json, projects/customizations-example/src/app/app.component.html, projects/customizations-example/src/app/app.component.ts, projects/customizations-example/src/app/app.module.ts, projects/customizations-example/src/app/message-text/message-text.component.html, projects/customizations-example/src/app/message-text/message-text.component.scss, projects/customizations-example/src/app/message-text/message-text.component.ts, projects/stream-chat-angular/src/lib/custom-templates.service.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.html, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts, projects/stream-chat-angular/src/lib/message-text/message-text.component.html, projects/stream-chat-angular/src/lib/message-text/message-text.component.spec.ts, projects/stream-chat-angular/src/lib/message-text/message-text.component.ts, projects/stream-chat-angular/src/lib/message/message.component.html, projects/stream-chat-angular/src/lib/message/message.component.spec.ts, projects/stream-chat-angular/src/lib/message/message.component.ts, projects/stream-chat-angular/src/lib/stream-chat.module.ts, projects/stream-chat-angular/src/lib/types.ts, projects/stream-chat-angular/src/public-api.ts
=> feat: create message-text component

projects/stream-chat-angular/src/lib/message/message.component.ts
https://linear.app/stream/issue/ANG-44/message-actions-reopened-after-adding-reaction
=> fix: message menu reopened after adding reaction

projects/stream-chat-angular/src/lib/channel.service.ts, projects/stream-chat-angular/src/lib/channel/channel.component.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.spec.ts, projects/stream-chat-angular/src/lib/message-input/message-input.component.ts, projects/stream-chat-angular/src/lib/message-list/message-list.component.ts, projects/stream-chat-angular/src/lib/message/message.component.ts
https://linear.app/stream/issue/ANG-40/emit-activechanneldollar-on-every-ws-event
=> Emit active channel on all ws events
